# Generated by Django 4.1.13 on 2024-09-13 11:05

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_coords', djongo.models.fields.JSONField()),
                ('end_coords', djongo.models.fields.JSONField()),
                ('stops', djongo.models.fields.JSONField()),
                ('driver_details', djongo.models.fields.JSONField()),
            ],
        ),
    ]
