# Generated by Django 4.1.13 on 2024-09-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
