# Generated by Django 4.1.13 on 2024-08-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dboperations', '0002_loginuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='password',
        ),
        migrations.AddField(
            model_name='loginuser',
            name='exemail',
            field=models.EmailField(default=None, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loginuser',
            name='expassword',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
