# Generated by Django 4.1.13 on 2024-09-13 11:05

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dboperations', '0003_remove_loginuser_email_remove_loginuser_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('destinations', models.CharField(max_length=255)),
                ('stops', djongo.models.fields.JSONField()),
                ('radio_choice', models.IntegerField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3')])),
                ('is_checked', models.BooleanField(default=False)),
            ],
        ),
    ]
