# Generated by Django 4.1.13 on 2024-09-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dboperations', '0004_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='DriverEmail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='Drivername',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
