# Generated by Django 4.1.13 on 2024-09-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dboperations', '0005_driver_driveremail_driver_drivername'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='Price',
            field=models.IntegerField(blank=True, max_length=1000, null=True),
        ),
    ]
