# Generated by Django 4.1.13 on 2024-09-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dboperations', '0006_driver_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginUser',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='driver',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
